-- 코드를 입력하세요
WITH RECURSIVE H AS(
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1
    FROM H
    WHERE NUM < 23
)

SELECT H.NUM AS HOUR, SUM(COALESCE(COUNT,0)) AS COUNT
FROM H
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
           FROM ANIMAL_OUTS
           GROUP BY HOUR(DATETIME)) AS A
ON H.NUM = A.HOUR
GROUP BY H.NUM
ORDER BY HOUR ASC;